#!/bin/bash
 
# Script for getting http response time
#
# @author: Tuan Hoang
# 17 May 2024
#

# Threshold for http response time at which the working instance will trigger memory dump 
export threshold=$1

# Instance name or ID
export instance=$2

# URL to monitor HTTP Response time for
export url=$3

# Read HTTP Response time & Status code into separated variables
read -r respTimeInSeconds httpCode <<< $(curl -so /dev/null -w "%{time_total} %{http_code}" $url)

# Convert to miliseconds
respTimeinMiliSeconds=$(echo "$respTimeInSeconds*1000/1" | bc)

echo "$(date '+%Y-%m-%d %H:%M:%S'): Response Time $respTimeinMiliSeconds (ms), Status Code $httpCode"

# Trigger memory dump if HTTP response time reaches the threshold & HTTP code is in [200, 301, 302]  
if [[ ("$respTimeinMiliSeconds" -ge "$threshold") && ("$httpCode" -eq 200 || "$httpCode" -eq 301 || "$httpCode" -eq 302) ]]; then
    if [[ ! -e "dump_taken.lock" ]]; then
        echo "Acquiring lock..." && touch "dump_taken.lock" && echo "Memory dump is generated by $instance" >> dump_taken.lock
        echo "Taking memory dump...."
        nohup /tools/dotnet-dump collect -p $(/tools/dotnet-dump ps | grep /usr/share/dotnet/dotnet | grep -v grep | tr -s " " | cut -d" " -f2) &
    fi 
fi
